version: '3.7'

services:

  database:
    image: postgres
    container_name: database_converter
    restart: always
    ports:
      - '5444:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=currency_converter
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_converter
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DEFAULT_EMAIL=root@thaisminas.com
    depends_on:
      - database

volumes:
  pgdata:
